// Generated by wxt
export {}
declare global {
  const ContentScriptContext: typeof import('wxt/client')['ContentScriptContext']
  const InvalidMatchPattern: typeof import('wxt/sandbox')['InvalidMatchPattern']
  const MatchPattern: typeof import('wxt/sandbox')['MatchPattern']
  const MigrationError: typeof import('wxt/storage')['MigrationError']
  const Toolbar: typeof import('/Users/mohammadomar/Documents/Personal Projects/proofly/components/Toolbar')['Toolbar']
  const browser: typeof import('wxt/browser')['browser']
  const clearCanvas: typeof import('/Users/mohammadomar/Documents/Personal Projects/proofly/utils/canvas')['clearCanvas']
  const createIframeUi: typeof import('wxt/client')['createIframeUi']
  const createIntegratedUi: typeof import('wxt/client')['createIntegratedUi']
  const createShadowRootUi: typeof import('wxt/client')['createShadowRootUi']
  const defineAppConfig: typeof import('wxt/sandbox')['defineAppConfig']
  const defineBackground: typeof import('wxt/sandbox')['defineBackground']
  const defineConfig: typeof import('wxt')['defineConfig']
  const defineContentScript: typeof import('wxt/sandbox')['defineContentScript']
  const defineUnlistedScript: typeof import('wxt/sandbox')['defineUnlistedScript']
  const defineWxtPlugin: typeof import('wxt/sandbox')['defineWxtPlugin']
  const drawHighlighter: typeof import('/Users/mohammadomar/Documents/Personal Projects/proofly/utils/canvas')['drawHighlighter']
  const drawHighlighterPath: typeof import('/Users/mohammadomar/Documents/Personal Projects/proofly/utils/canvas')['drawHighlighterPath']
  const drawLine: typeof import('/Users/mohammadomar/Documents/Personal Projects/proofly/utils/canvas')['drawLine']
  const drawShape: typeof import('/Users/mohammadomar/Documents/Personal Projects/proofly/utils/canvas')['drawShape']
  const drawText: typeof import('/Users/mohammadomar/Documents/Personal Projects/proofly/utils/canvas')['drawText']
  const fakeBrowser: typeof import('wxt/testing')['fakeBrowser']
  const getColorValue: typeof import('/Users/mohammadomar/Documents/Personal Projects/proofly/utils/canvas')['getColorValue']
  const getHighlighterColorValue: typeof import('/Users/mohammadomar/Documents/Personal Projects/proofly/utils/canvas')['getHighlighterColorValue']
  const injectScript: typeof import('wxt/client')['injectScript']
  const storage: typeof import('wxt/storage')['storage']
  const useAppConfig: typeof import('wxt/client')['useAppConfig']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Tool, Color, ShapeMode, PenWidth, DrawingState, Point } from '/Users/mohammadomar/Documents/Personal Projects/proofly/utils/types'
  import('/Users/mohammadomar/Documents/Personal Projects/proofly/utils/types')
}
